# Generated by Django 2.2.13 on 2020-07-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200704_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Blog'),
        ),
    ]
