# Generated by Django 2.2 on 2020-07-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200704_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
